language: cpp
compiler:
  - clang
  - gcc

sudo: required
dist: bionic
cache: ccache

addons:
  apt:
    packages:
      - cmake
      - libalure-dev
      - libboost-thread1.65-dev
      - libboost-system1.65-dev
      - libboost-filesystem1.65-dev
      - libcurl4-openssl-dev
      - libjsoncpp-dev
      - liblua5.1-0-dev
      - libssl-dev
      - libzip-dev
      - spring
      - zlib1g-dev
      - libgit2-dev

before_script:
  - cmake . -DPRD_DEVELOP_FILES:BOOL=ON -DBUILD_TESTS=ON -DPRD_ENABLE_LSL=ON -DRAPIDTOOLS:BOOL=ON -DLSLSERVER:BOOL=ON 
# -DLSL_EXTRACT:BOOL=ON

script:
  - make -j2
  - sudo make install
  - src/pr-downloader dev-game:test
  - src/pr-downloader --rapid-validate
